/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthMemberRouteRouteImport } from './routes/_auth/_member/route'
import { Route as ApiCronSyncRouteImport } from './routes/api/cron/sync'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthMemberProfileRouteImport } from './routes/_auth/_member/profile'
import { Route as AuthMemberMatchesRouteImport } from './routes/_auth/_member/matches'
import { Route as AuthMemberLeaderboardRouteImport } from './routes/_auth/_member/leaderboard'
import { Route as AuthMemberAdminRouteImport } from './routes/_auth/_member/admin'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthMemberRouteRoute = AuthMemberRouteRouteImport.update({
  id: '/_member',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiCronSyncRoute = ApiCronSyncRouteImport.update({
  id: '/api/cron/sync',
  path: '/api/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMemberProfileRoute = AuthMemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthMemberRouteRoute,
} as any)
const AuthMemberMatchesRoute = AuthMemberMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthMemberRouteRoute,
} as any)
const AuthMemberLeaderboardRoute = AuthMemberLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthMemberRouteRoute,
} as any)
const AuthMemberAdminRoute = AuthMemberAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthMemberRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/admin': typeof AuthMemberAdminRoute
  '/leaderboard': typeof AuthMemberLeaderboardRoute
  '/matches': typeof AuthMemberMatchesRoute
  '/profile': typeof AuthMemberProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/admin': typeof AuthMemberAdminRoute
  '/leaderboard': typeof AuthMemberLeaderboardRoute
  '/matches': typeof AuthMemberMatchesRoute
  '/profile': typeof AuthMemberProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/_member': typeof AuthMemberRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/_member/admin': typeof AuthMemberAdminRoute
  '/_auth/_member/leaderboard': typeof AuthMemberLeaderboardRoute
  '/_auth/_member/matches': typeof AuthMemberMatchesRoute
  '/_auth/_member/profile': typeof AuthMemberProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/api/auth/$'
    | '/api/cron/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/api/auth/$'
    | '/api/cron/sync'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/_member'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/_member/admin'
    | '/_auth/_member/leaderboard'
    | '/_auth/_member/matches'
    | '/_auth/_member/profile'
    | '/api/auth/$'
    | '/api/cron/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSyncRoute: typeof ApiCronSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/_member': {
      id: '/_auth/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthMemberRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/cron/sync': {
      id: '/api/cron/sync'
      path: '/api/cron/sync'
      fullPath: '/api/cron/sync'
      preLoaderRoute: typeof ApiCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_member/profile': {
      id: '/_auth/_member/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthMemberProfileRouteImport
      parentRoute: typeof AuthMemberRouteRoute
    }
    '/_auth/_member/matches': {
      id: '/_auth/_member/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthMemberMatchesRouteImport
      parentRoute: typeof AuthMemberRouteRoute
    }
    '/_auth/_member/leaderboard': {
      id: '/_auth/_member/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthMemberLeaderboardRouteImport
      parentRoute: typeof AuthMemberRouteRoute
    }
    '/_auth/_member/admin': {
      id: '/_auth/_member/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthMemberAdminRouteImport
      parentRoute: typeof AuthMemberRouteRoute
    }
  }
}

interface AuthMemberRouteRouteChildren {
  AuthMemberAdminRoute: typeof AuthMemberAdminRoute
  AuthMemberLeaderboardRoute: typeof AuthMemberLeaderboardRoute
  AuthMemberMatchesRoute: typeof AuthMemberMatchesRoute
  AuthMemberProfileRoute: typeof AuthMemberProfileRoute
}

const AuthMemberRouteRouteChildren: AuthMemberRouteRouteChildren = {
  AuthMemberAdminRoute: AuthMemberAdminRoute,
  AuthMemberLeaderboardRoute: AuthMemberLeaderboardRoute,
  AuthMemberMatchesRoute: AuthMemberMatchesRoute,
  AuthMemberProfileRoute: AuthMemberProfileRoute,
}

const AuthMemberRouteRouteWithChildren = AuthMemberRouteRoute._addFileChildren(
  AuthMemberRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthMemberRouteRoute: typeof AuthMemberRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthMemberRouteRoute: AuthMemberRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSyncRoute: ApiCronSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
